// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: square-line-ui

#include "ui.h"

lv_obj_t * uic_appmenu;
lv_obj_t * ui_appmenu = NULL;
lv_obj_t * ui_Calendar1 = NULL;
// event funtions

// build funtions

void ui_appmenu_screen_init(void)
{
    ui_appmenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_appmenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar1 = lv_calendar_create(ui_appmenu);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 230);
    lv_obj_set_height(ui_Calendar1, 240);
    lv_obj_set_x(ui_Calendar1, 1);
    lv_obj_set_y(ui_Calendar1, -10);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);

    uic_appmenu = ui_appmenu;

}

void ui_appmenu_screen_destroy(void)
{
    if(ui_appmenu) lv_obj_del(ui_appmenu);

    // NULL screen variables
    uic_appmenu = NULL;
    ui_appmenu = NULL;
    ui_Calendar1 = NULL;

}
