// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: square-line-ui

#ifndef UI_APPMENU_H
#define UI_APPMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_appmenu
extern void ui_appmenu_screen_init(void);
extern void ui_appmenu_screen_destroy(void);
extern lv_obj_t * ui_appmenu;
extern lv_obj_t * ui_Calendar1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_appmenu;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

