// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: square-line-ui

#include "ui.h"
#include "app/app.h"

void ui_event_button_clicked(lv_event_t * e)
{
	// Your code here
	app_show_appmenu();
}
