// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: square-line-ui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_button_clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
