// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: square-line-ui

#include "ui.h"

lv_obj_t * uic_button;
lv_obj_t * uic_watchface;
lv_obj_t * ui_watchface = NULL;
lv_obj_t * ui_button = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_button_clicked(e);
    }
}

// build funtions

void ui_watchface_screen_init(void)
{
    ui_watchface = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_watchface, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_button = lv_btn_create(ui_watchface);
    lv_obj_set_width(ui_button, 100);
    lv_obj_set_height(ui_button, 50);
    lv_obj_set_x(ui_button, 7);
    lv_obj_set_y(ui_button, 100);
    lv_obj_set_align(ui_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_watchface);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 8);
    lv_obj_set_y(ui_Label1, 99);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Button");

    lv_obj_add_event_cb(ui_button, ui_event_button, LV_EVENT_ALL, NULL);
    uic_watchface = ui_watchface;
    uic_button = ui_button;

}

void ui_watchface_screen_destroy(void)
{
    if(ui_watchface) lv_obj_del(ui_watchface);

    // NULL screen variables
    uic_watchface = NULL;
    ui_watchface = NULL;
    uic_button = NULL;
    ui_button = NULL;
    ui_Label1 = NULL;

}
