// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: square-line-ui

#ifndef UI_WATCHFACE_H
#define UI_WATCHFACE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_watchface
extern void ui_watchface_screen_init(void);
extern void ui_watchface_screen_destroy(void);
extern lv_obj_t * ui_watchface;
extern void ui_event_button(lv_event_t * e);
extern lv_obj_t * ui_button;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_watchface;
extern lv_obj_t * uic_button;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

